# From https://docs.google.com/spreadsheets/d/1jdTilDL19d66Yqw-wC0PsK8CGEnyyfuIB_zv8cszfpY/edit?gid=80002800#gid=80002800
#  from https://zenodo.org/records/7151870, https://zenodo.org/records/6948238
# Columns: DFG_notation_2014	DFG_name_2014	OECD_notation_2006	OECD_name_2006
mapping = [
    ("101","Ancient Cultures","6.1","History and archaeology"),
    ("101","Ancient Cultures","6.2","Languages and literature"),
    ("10101","Prehistory","6.1","History and archaeology"),
    ("10102","Classical Philology","6.2","Languages and literature"),
    ("10103","Ancient History","6.1","History and archaeology"),
    ("10104","Classical Archaeology","6.1","History and archaeology"),
    ("10105","Egyptology and Ancient Near Eastern Studies","6.1","History and archaeology"),
    ("102","History","6.1","History and archaeology"),
    ("10201","Medieval History","6.1","History and archaeology"),
    ("10202","Early Modern History","6.1","History and archaeology"),
    ("10203","Modern and Current History","6.1","History and archaeology"),
    ("10204","History of Science","6.3","Philosophy, ethics and religion"),
    ("103","Fine Arts, Music, Theatre and Media Studies","6.4","Art (arts, history of arts, performing arts, music)"),
    ("10301","Art History","6.4","Art (arts, history of arts, performing arts, music)"),
    ("10302","Musicology","6.4","Art (arts, history of arts, performing arts, music)"),
    ("10303","Theatre and Media Studies","6.4","Art (arts, history of arts, performing arts, music)"),
    ("104","Linguistics","6.2","Languages and literature"),
    ("10401","General and Applied Linguistics","6.2","Languages and literature"),
    ("10402","Individual Linguistics","6.2","Languages and literature"),
    ("10403","Typology, NonEuropean Languages, Historical Linguistics","6.2","Languages and literature"),
    ("105","Literary Studies","6.2","Languages and literature"),
    ("10501","Medieval German Literature","6.2","Languages and literature"),
    ("10502","Modern German Literature","6.2","Languages and literature"),
    ("10503","European and American Literature","6.2","Languages and literature"),
    ("10504","General and Comparative Literature and Cultural Studies","6.2","Languages and literature"),
    ("106","NonEuropean Languages and Cultures, Social and Cultural Anthropology, Jewish Studies and Religious Studies","6.3","Philosophy, ethics and religion"),
    ("106","NonEuropean Languages and Cultures, Social and Cultural Anthropology, Jewish Studies and Religious Studies","5.4","Sociology"),
    ("106","NonEuropean Languages and Cultures, Social and Cultural Anthropology, Jewish Studies and Religious Studies","6.2","Languages and literature"),
    ("10601","Social and Cultural Anthropology and Ethnology/Folklore","5.4","Sociology"),
    ("10602","Asian Studies","6.5","Other humanities"),
    ("10602","Asian Studies","6.2","Languages and literature"),
    ("10602","Asian Studies","5.4","Sociology"),
    ("10603","African, American and Oceania Studies","6.5","Other humanities"),
    ("10603","African, American and Oceania Studies","6.2","Languages and literature"),
    ("10603","African, American and Oceania Studies","5.4","Sociology"),
    ("10604","Islamic Studies, Arabian Studies, Semitic Studies","6.3","Philosophy, ethics and religion"),
    ("10604","Islamic Studies, Arabian Studies, Semitic Studies","6.2","Languages and literature"),
    ("10604","Islamic Studies, Arabian Studies, Semitic Studies","5.4","Sociology"),
    ("10605","Religious Studies and Jewish Studies","6.3","Philosophy, ethics and religion"),
    ("10605","Religious Studies and Jewish Studies","6.2","Languages and literature"),
    ("10605","Religious Studies and Jewish Studies","5.4","Sociology"),
    ("107","Theology","6.3","Philosophy, ethics and religion"),
    ("10701","Protestant Theology","6.3","Philosophy, ethics and religion"),
    ("10702","Roman Catholic Theology","6.3","Philosophy, ethics and religion"),
    ("108","Philosophy","6.3","Philosophy, ethics and religion"),
    ("10801","History of Philosophy","6.3","Philosophy, ethics and religion"),
    ("10802","Theoretical Philosophy","6.3","Philosophy, ethics and religion"),
    ("10803","Practical Philosophy","6.3","Philosophy, ethics and religion"),
    ("109","Education Sciences","5.3","Educational sciences"),
    ("10901","General Education and History of Education","5.3","Educational sciences"),
    ("10902","Research on Teaching, Learning, and Training","5.3","Educational sciences"),
    ("10903","Research on Socialization and Educational Institutions and Professions","5.3","Educational sciences"),
    ("110","Psychology","5.1","Psychology"),
    ("11001","General, Biological and Mathematical Psychology","5.1","Psychology"),
    ("11002","Developmental and Educational Psychology","5.1","Psychology"),
    ("11002","Developmental and Educational Psychology","5.3","Educational sciences"),
    ("11003","Social Psychology, Industrial and Organisational Psychology","5.1","Psychology"),
    ("11004","Differential Psychology, Clinical Psychology, Medical Psychology, Methodology","5.1","Psychology"),
    ("111","Social Sciences","5","Social sciences "),
    ("11101","Sociological Theory","5.4","Sociology"),
    ("11102","Empirical Social Research","5.4","Sociology"),
    ("11102","Empirical Social Research","5.9","Other social sciences"),
    ("11103","Communication Sciences","5.8","Media and communications"),
    ("11104","Political Science","5.6","Political Science"),
    ("112","Economics","5.2","Economics and business"),
    ("11201","Economic Theory","5.2","Economics and business"),
    ("11202","Economic and Social Policy","5.2","Economics and business"),
    ("11203","Public Finance","5.6","Political Science"),
    ("11203","Public Finance","5.2","Economics and business"),
    ("11204","Business Administration","5.2","Economics and business"),
    ("11205","Statistics and Econometrics","5.2","Economics and business"),
    ("11206","Economic and Social History","5.2","Economics and business"),
    ("113","Jurisprudence","5.5","Law"),
    ("11301","Legal and Political Philosophy, Legal History, Legal Theory","5.5","Law"),
    ("11302","Private Law","5.5","Law"),
    ("11303","Public Law","5.5","Law"),
    ("11304","Criminal Law and Law of Criminal Procedure","5.5","Law"),
    ("11305","Criminology","5.5","Law"),
    ("201","Basic Biological and Medical Research","1.6","Biological sciences"),
    ("20101","Biochemistry","1.6","Biological sciences"),
    ("20102","Biophysics","1.6","Biological sciences"),
    ("20103","Cell Biology","1.6","Biological sciences"),
    ("20104","Structural Biology","1.6","Biological sciences"),
    ("20105","General Genetics","1.6","Biological sciences"),
    ("20106","Developmental Biology","1.6","Biological sciences"),
    ("20107","Bioinformatics and Theoretical Biology","1.6","Biological sciences"),
    ("20107","Bioinformatics and Theoretical Biology","1.2","Computer and information sciences"),
    ("20108","Anatomy","1.6","Biological sciences"),
    ("20108","Anatomy","3.1","Basic medicine"),
    ("202","Plant Sciences","1.6","Biological sciences"),
    ("20201","Plant Systematics and Evolution","1.6","Biological sciences"),
    ("20202","Plant Ecology and Ecosystem Analysis","1.6","Biological sciences"),
    ("20203","Interorganismic Interactions of Plants","1.6","Biological sciences"),
    ("20204","Plant Physiology","1.6","Biological sciences"),
    ("20205","Plant Biochemistry and Biophysics","1.6","Biological sciences"),
    ("20206","Plant Cell and Developmental Biology","1.6","Biological sciences"),
    ("20207","Â Plant Genetics","1.6","Biological sciences"),
    ("203","Zoology","1.6","Biological sciences"),
    ("20301","Systematics and Morphology","1.6","Biological sciences"),
    ("20302","Evolution, Anthropology","1.6","Biological sciences"),
    ("20303","Animal Ecology, Biodiversity and Ecosystem Research","1.6","Biological sciences"),
    ("20304","Sensory and Behavioural Biology","1.6","Biological sciences"),
    ("20305","Biochemistry and Animal Physiology","1.6","Biological sciences"),
    ("20306","Animal Genetics, Cell and Developmental Biology","1.6","Biological sciences"),
    ("204","Microbiology, Virology and Immunology","1.6","Biological sciences"),
    ("204","Microbiology, Virology and Immunology","3.1","Basic medicine"),
    ("204","Microbiology, Virology and Immunology","3.3","Health sciences"),
    ("20401","Metabolism, Biochemistry and Genetics of Microorganisms","1.6","Biological sciences"),
    ("20402","Microbial Ecology and Applied Microbiology","1.6","Biological sciences"),
    ("20403","Medical Microbiology, Molecular Infection Biology","3.1","Basic medicine"),
    ("20403","Medical Microbiology, Molecular Infection Biology","1.6","Biological sciences"),
    ("20404","Virology","1.6","Biological sciences"),
    ("20405","Immunology","3.1","Basic medicine"),
    ("205","Medicine","3.1","Basic medicine"),
    ("205","Medicine","1.6","Biological sciences"),
    ("20501","Epidemiology, Medical Biometry, Medical Informatics","3.3","Health sciences"),
    ("20501","Epidemiology, Medical Biometry, Medical Informatics","1.2","Computer and information sciences"),
    ("20502","Public Health, Health Services Research, Social Medicine","3.3","Health sciences"),
    ("20503","Human Genetics","1.6","Biological sciences"),
    ("20503","Human Genetics","3.1","Basic medicine"),
    ("20504","Physiology","3.1","Basic medicine"),
    ("20505","Nutritional Sciences","3.3","Health sciences"),
    ("20506","Pathology and Forensic Medicine","3.1","Basic medicine"),
    ("20506","Pathology and Forensic Medicine","3.5","Other medical sciences"),
    ("20507","Clinical Chemistry and Pathobiochemistry","3.1","Basic medicine"),
    ("20507","Clinical Chemistry and Pathobiochemistry","2.6","Medical engineering"),
    ("20508","Pharmacy","3.1","Basic medicine"),
    ("20509","Pharmacology","3.1","Basic medicine"),
    ("20510","Toxicology and Occupational Medicine","3.1","Basic medicine"),
    ("20511","Anaesthesiology","3.2","Clinical medicine"),
    ("20512","Cardiology, Angiology","3.2","Clinical medicine"),
    ("20513","Pneumology, Clinical Infectiology, Intensive Care Medicine","3.2","Clinical medicine"),
    ("20514","Hematology, Oncology, Transfusion Medicine","3.2","Clinical medicine"),
    ("20515","Gastroenterology, Metabolism","3.2","Clinical medicine"),
    ("20516","Nephrology","3.2","Clinical medicine"),
    ("20517","Endocrinology, Diabetology","3.2","Clinical medicine"),
    ("20518","Rheumatology, Clinical Immunology, Allergology","3.2","Clinical medicine"),
    ("20519","Dermatology","3.2","Clinical medicine"),
    ("20520","Pediatric and Adolescent Medicine","3.2","Clinical medicine"),
    ("20521","Gynaecology and Obstetrics","3.2","Clinical medicine"),
    ("20522","Reproductive Medicine/Biology","3.2","Clinical medicine"),
    ("20522","Reproductive Medicine/Biology","1.6","Biological sciences"),
    ("20523","Urology","3.2","Clinical medicine"),
    ("20524","Gerontology and Geriatric Medicine","3.2","Clinical medicine"),
    ("20525","Vascular and Visceral Surgery","3.2","Clinical medicine"),
    ("20526","Cardiothoracic Surgery","3.2","Clinical medicine"),
    ("20527","Traumatology and Orthopaedics","3.2","Clinical medicine"),
    ("20528","Dentistry, Oral Surgery","3.2","Clinical medicine"),
    ("20529","Otolaryngology","3.2","Clinical medicine"),
    ("20530","Radiology and Nuclear Medicine","3.2","Clinical medicine"),
    ("20531","Radiation Oncology and Radiobiology","3.2","Clinical medicine"),
    ("20532","Biomedical Technology and Medical Physics","3.4","Health biotechnology"),
    ("206","Neurosciences","3.1","Basic medicine"),
    ("206","Neurosciences","1.6","Biological sciences"),
    ("20601","Molecular Neuroscience and Neurogenetics","3.1","Basic medicine"),
    ("20601","Molecular Neuroscience and Neurogenetics","1.6","Biological sciences"),
    ("20602","Cellular Neuroscience","3.1","Basic medicine"),
    ("20602","Cellular Neuroscience","1.6","Biological sciences"),
    ("20603","Developmental Neurobiology","1.6","Biological sciences"),
    ("20604","Systemic Neuroscience, Computational Neuroscience, Behaviour","1.6","Biological sciences"),
    ("20604","Systemic Neuroscience, Computational Neuroscience, Behaviour","3.1","Basic medicine"),
    ("20604","Systemic Neuroscience, Computational Neuroscience, Behaviour","1.2","Computer and information sciences "),
    ("20605","Comparative Neurobiology","1.6","Biological sciences"),
    ("20605","Comparative Neurobiology","3.1","Basic medicine"),
    ("20606","Cognitive Neuroscience and Neuroimaging","3.1","Basic medicine"),
    ("20606","Cognitive Neuroscience and Neuroimaging","1.6","Biological sciences"),
    ("20606","Cognitive Neuroscience and Neuroimaging","3.2","Clinical medicine"),
    ("20607","Molecular Neurology","3.2","Clinical medicine"),
    ("20607","Molecular Neurology","1.6","Biological sciences"),
    ("20608","Clinical Neurosciences I Neurology, Neurosurgery","3.2","Clinical medicine"),
    ("20609","Biological Psychiatry","3.2","Clinical medicine"),
    ("20609","Biological Psychiatry","3.1","Basic medicine"),
    ("20610","Clinical Neurosciences II Psychiatry, Psychotherapy, Psychosomatic Medicine","3.2","Clinical medicine"),
    ("20611","Clinical Neurosciences III Ophthalmology","3.2","Clinical medicine"),
    ("207","Agriculture, Forestry, Horticulture and Veterinary Medicine","4.1","Agriculture, forestry, and fisheries"),
    ("20701","Soil Sciences","4.1","Agriculture, forestry, and fisheries"),
    ("20702","Plant Cultivation","4.1","Agriculture, forestry, and fisheries"),
    ("20703","Plant Nutrition","4.1","Agriculture, forestry, and fisheries"),
    ("20704","Ecology of Agricultural Landscapes","4.5","Other agricultural sciences"),
    ("20705","Plant Breeding","4.1","Agriculture, forestry, and fisheries"),
    ("20706","Phytomedicine","3.1","Basic medicine"),
    ("20707","Agricultural and Food Process Engineering","2.11","Other engineering and technologies"),
    ("20708","Agricultural Economics and Sociology","4.5","Other agricultural sciences"),
    ("20709","Inventory, Control and Use of Forest Resources","4.1","Agriculture, forestry, and fisheries"),
    ("20710","Basic Forest Research","4.1","Agriculture, forestry, and fisheries"),
    ("20711","Animal Husbandry, Breeding and Hygiene","4.2","Animal and dairy science"),
    ("20712","Animal Nutrition and Nutrition Physiology","4.2","Animal and dairy science"),
    ("20713","Basic Veterinary Medical Science","4.3","Veterinary science"),
    ("20714","Basic Research on Pathogenesis, Diagnostics and Therapy and Clinical Veterinary Medicine","4.3","Veterinary science"),
    ("301","Molecular Chemistry","1.4","Chemical sciences"),
    ("30101","Inorganic Molecular Chemistry","1.4","Chemical sciences"),
    ("30102","Organic Molecular Chemistry","1.4","Chemical sciences"),
    ("302","Chemical Solid State and Surface Research","1.4","Chemical sciences"),
    ("30201","Solid State and Surface Chemistry, Material Synthesis","1.4","Chemical sciences"),
    ("30201","Solid State and Surface Chemistry, Material Synthesis","2.4","Chemical engineering"),
    ("30202","Physical Chemistry of Solids and Surfaces, Material Characterisation","1.4","Chemical sciences"),
    ("30203","Theory and Modelling","1.4","Chemical sciences"),
    ("303","Physical and Theoretical Chemistry","1.4","Chemical sciences"),
    ("30301","Physical Chemistry of Molecules, Interfaces and Liquids Spectroscopy, Kinetics","1.4","Chemical sciences"),
    ("30302","General Theoretical Chemistry","1.4","Chemical sciences"),
    ("304","Analytical Chemistry, Method Development (Chemistry)","1.4","Chemical sciences"),
    ("30401","Analytical Chemistry, Method Development (Chemistry)","1.4","Chemical sciences"),
    ("305","Biological Chemistry and Food Chemistry","1.4","Chemical sciences"),
    ("305","Biological Chemistry and Food Chemistry","1.6","Biological sciences"),
    ("30501","Biological and Biomimetic Chemistry","1.4","Chemical sciences"),
    ("30501","Biological and Biomimetic Chemistry","1.6","Biological sciences"),
    ("30502","Food Chemistry","1.4","Chemical sciences"),
    ("30502","Food Chemistry","1.6","Biological sciences"),
    ("306","Polymer Research","1.4","Chemical sciences"),
    ("30601","Preparatory and Physical Chemistry of Polymers","1.4","Chemical sciences"),
    ("30602","Experimental and Theoretical Physics of Polymers","1.4","Chemical sciences"),
    ("30603","Polymer Materials","2.5","Materials engineering"),
    ("30603","Polymer Materials","1.4","Chemical sciences"),
    ("307","Condensed Matter Physics","1.3","Physical sciences"),
    ("30701","Experimental Condensed Matter Physics","1.3","Physical sciences"),
    ("30702","Theoretical Condensed Matter Physics","1.3","Physical sciences"),
    ("308","Optics, Quantum Optics and Physics of Atoms, Molecules and Plasmas","1.3","Physical sciences"),
    ("30801","Optics, Quantum Optics, Atoms, Molecules, Plasmas","1.3","Physical sciences"),
    ("309","Particles, Nuclei and Fields","1.3","Physical sciences"),
    ("30901","Particles, Nuclei and Fields","1.3","Physical sciences"),
    ("310","Statistical Physics, Soft Matter, Biological Physics, Nonlinear Dynamics","1.3","Physical sciences"),
    ("310","Statistical Physics, Soft Matter, Biological Physics, Nonlinear Dynamics","1.4","Chemical sciences"),
    ("31001","Statistical Physics, Soft Matter, Biological Physics, Nonlinear Dynamics","1.3","Physical sciences"),
    ("31001","Statistical Physics, Soft Matter, Biological Physics, Nonlinear Dynamics","1.4","Chemical sciences"),
    ("311","Astrophysics and Astronomy","1.3","Physical sciences"),
    ("31101","Astrophysics and Astronomy","1.3","Physical sciences"),
    ("312","Mathematics","1.1","Mathematics"),
    ("31201","Mathematics","1.1","Mathematics"),
    ("313","Atmospheric Science and Oceanography","1.5","Earth and related environmental sciences"),
    ("31301","Atmospheric Science","1.5","Earth and related environmental sciences"),
    ("31302","Oceanography","1.5","Earth and related environmental sciences"),
    ("314","Geology and Palaeontology","1.5","Earth and related environmental sciences"),
    ("31401","Geology and Palaeontology","1.5","Earth and related environmental sciences"),
    ("315","Geophysics and Geodesy","1.5","Earth and related environmental sciences"),
    ("31501","Geophysics","1.5","Earth and related environmental sciences"),
    ("31502","Geodesy, Photogrammetry, Remote Sensing, Geoinformatics, Cartography","1.5","Earth and related environmental sciences"),
    ("31502","Geodesy, Photogrammetry, Remote Sensing, Geoinformatics, Cartography","2.7","Environmental engineering"),
    ("31502","Geodesy, Photogrammetry, Remote Sensing, Geoinformatics, Cartography","1.2","Computer and information sciences"),
    ("316","Geochemistry, Mineralogy and Crystallography","1.5","Earth and related environmental sciences"),
    ("31601","Geochemistry, Mineralogy and Crystallography","1.5","Earth and related environmental sciences"),
    ("317","Geography","1.5","Earth and related environmental sciences"),
    ("317","Geography","5.7","Social and economic geography"),
    ("31701","Physical Geography","1.5","Earth and related environmental sciences"),
    ("31702","Human Geography","5.7","Social and economic geography"),
    ("318","Water Research","1.5","Earth and related environmental sciences"),
    ("31801","Hydrogeology, Hydrology, Limnology, Urban Water Management, Water Chemistry, Integrated Water Resources","1.5","Earth and related environmental sciences"),
    ("401","Production Technology","2.3","Mechanical engineering"),
    ("401","Production Technology","2.5","Materials engineering"),
    ("40101","MetalCutting Manufacturing Engineering","2.3","Mechanical engineering"),
    ("40102","Primary Shaping and Reshaping Technology","2.3","Mechanical engineering"),
    ("40103","Micro, Precision, Mounting, Joining, Separation Technology","2.3","Mechanical engineering"),
    ("40104","Plastics Engineering","2.5","Materials engineering"),
    ("40105","Production Automation, Factory Operation, Operations Management","2.3","Mechanical engineering"),
    ("40105","Production Automation, Factory Operation, Operations Management","2.2","Electrical engineering, Electronic engineering, Information engineering"),
    ("402","Mechanics and Constructive Mechanical Engineering","2.3","Mechanical engineering"),
    ("40201","Construction, Machine Elements","2.3","Mechanical engineering"),
    ("40202","Mechanics","2.3","Mechanical engineering"),
    ("40203","Lightweight Construction, Textile Technology","2.5","Materials engineering"),
    ("40204","Acoustics","2.3","Mechanical engineering"),
    ("40204","Acoustics","1.3","Physical sciences"),
    ("403","Process Engineering, Technical Chemistry","2.4","Chemical engineering"),
    ("40301","Chemical and Thermal Process Engineering","2.3","Mechanical engineering"),
    ("40301","Chemical and Thermal Process Engineering","2.4","Chemical engineering"),
    ("40302","Technical Chemistry","2.4","Chemical engineering"),
    ("40303","Mechanical Process Engineering","2.3","Mechanical engineering"),
    ("40304","Biological Process Engineering","2.9","Industrial biotechnology"),
    ("404","Heat Energy Technology, Thermal Machines, Fluid Mechanics","2.3","Mechanical engineering"),
    ("40401","Energy Process Engineering","2.3","Mechanical engineering"),
    ("40402","Technical Thermodynamics","2.3","Mechanical engineering"),
    ("40403","Fluid Mechanics","2.3","Mechanical engineering"),
    ("40404","Hydraulic and Turbo Engines and Piston Engines","2.3","Mechanical engineering"),
    ("405","Materials Engineering","2.5","Materials engineering"),
    ("40501","Metallurgical and Thermal Processes, Thermomechanical Treatment of Materials","2.5","Materials engineering"),
    ("40502","Sintered Metallic and Ceramic Materials","2.5","Materials engineering"),
    ("40503","Composite Materials","2.5","Materials engineering"),
    ("40504","Mechanical Behaviour of Construction Materials","2.5","Materials engineering"),
    ("40505","Coating and Surface Technology","2.5","Materials engineering"),
    ("406","Materials Science","2.5","Materials engineering"),
    ("40601","Thermodynamics and Kinetics of Materials","2.5","Materials engineering"),
    ("40602","Synthesis and Properties of Functional Materials","2.5","Materials engineering"),
    ("40603","Microstructural Mechanical Properties of Materials","2.5","Materials engineering"),
    ("40604","Structuring and Functionalisation","2.5","Materials engineering"),
    ("40605","Biomaterials","2.9","Industrial Biotechnology"),
    ("407","Systems Engineering","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40701","Automation, Control Systems, Robotics, Mechatronics","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40702","Measurement Systems","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40703","Microsystems","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40704","Traffic and Transport Systems, Logistics","2.1","Civil engineering"),
    ("40704","Traffic and Transport Systems, Logistics","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40705","Human Factors, Ergonomics, HumanMachine Systems","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("408","Electrical Engineering","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40801","Electronic Semiconductors, Components, Circuits, Systems","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40802","Communications, HighFrequency and Network Technology, Theoretical Electrical Engineering","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40803","Electrical Energy Generation, Distribution, Application","2.2","Electrical engineering, electronic engineering, information engineerin"),
    ("409","Computer Science","1.2","Computer and information sciences"),
    ("409","Computer Science","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("40901","Theoretical Computer Science","1.2","Computer and information sciences"),
    ("40902","Software Technology","1.2","Computer and information sciences"),
    ("40903","Operating, Communication and Information Systems","1.2","Computer and information sciences"),
    ("40904","Artificial Intelligence, Image and Language Processing","1.2","Computer and information sciences"),
    ("40905","Computer Architecture and Embedded Systems","2.2","Electrical engineering, electronic engineering, information engineering"),
    ("410","Construction Engineering and Architecture","2.1","Civil engineering"),
    ("41001","Architecture, Building and Construction History, Sustainable Building Technology, Building Design","2.1","Civil engineering"),
    ("41002","Urbanism, Spatial Planning, Transportation and Infrastructure Planning, Landscape Planning","2.7","Environmental engineering"),
    ("41002","Urbanism, Spatial Planning, Transportation and Infrastructure Planning, Landscape Planning","5.7","Social and economic geography"),
    ("41003","Construction Material Sciences, Chemistry, Building Physics","2.1","Civil engineering"),
    ("41003","Construction Material Sciences, Chemistry, Building Physics","2.5","Materials engineering"),
    ("41004","Structural Engineering, Building Informatics, Construction Operation","2.1","Civil engineering"),
    ("41005","Applied Mechanics, Statics and Dynamics","2.1","Civil engineering"),
    ("41006","Geotechnics, Hydraulic Engineering","2.7","Environmental engineering"),
]
