from rdflib import URIRef, Namespace

my_ns = Namespace('https://raw.githubusercontent.com/gonzatorte/aigdai-core/refs/heads/main/onto/owl/aigdai.owx#')
Organizacion = URIRef("#organizacion", my_ns)
Repositorio = URIRef("#repositorio", my_ns)
TipoDeIdDeOrganizacion = URIRef("#tipo_de_id_de_organizacion", my_ns)
Pais = URIRef("#pais", my_ns)
BloqueComercial = URIRef("#bloque_comercial", my_ns)
Planeta = URIRef("#planeta", my_ns)
Locacion = URIRef("#locacion", my_ns)
Disciplina = URIRef("#disciplina", my_ns)
es_sub_disciplina_de = URIRef("#es_sub_disciplina_de", my_ns)
esquema_de_disciplina = URIRef("#esquema_de_disciplina", my_ns)
nombre_de_disciplina = URIRef("#nombre_de_disciplina", my_ns)
MotorDeRepositorio = URIRef("#motor_de_repositorio", my_ns)
Certificacion = URIRef("#certificacion", my_ns)
utiliza_motor = URIRef('#utiliza_motor', my_ns)
repositorio_afin_a_disciplina = URIRef('#repositorio_afin_a_disciplina', my_ns)
tiene_nombre_organizacion = URIRef('#tiene_nombre_organizacion', my_ns)
se_ubica_en = URIRef('#se_ubica_en', my_ns)
incluido_en = URIRef('#incluido_en', my_ns)
alfa_3_de_pais = URIRef('#alfa_3_de_pais', my_ns)
nombre_de_pais = URIRef('#nombre_de_pais', my_ns)
nombre_de_bloque = URIRef('#nombre_de_bloque', my_ns)
es_organizacion_padre = URIRef('#es_organizacion_padre', my_ns) # ToDo: Make this relation Asymmetric e Irreflexiba?. Tb es_organizacion_antecesora?
es_organizacion_relacionada = URIRef('#es_organizacion_relacionada', my_ns)
organizacion_esta_activa = URIRef('#organizacion_esta_activa', my_ns)
organizacion_fundada_en_anio = URIRef('#organizacion_fundada_en_anio', my_ns)

tiene_nombre_repositorio = URIRef('#tiene_nombre_repositorio', my_ns)

principles_ns = Namespace('https://raw.githubusercontent.com/gonzatorte/aigdai-core/refs/heads/main/onto/owl/principles.owl#')
CriterioDeCalidad = URIRef("#criterio_de_calidad", principles_ns)
GrupoDeCriterio = URIRef("#grupo_de_criterio", principles_ns)
criterio_pertenece_a_grupo = URIRef("#criterio_pertenece_a_grupo", principles_ns)
extiende_de_criterio = URIRef("#extiende_de_criterio", principles_ns)
considera_criterio = URIRef("#considera_criterio", principles_ns)
criterio_tiene_descripcion = URIRef("#criterio_tiene_descripcion", principles_ns)

IdDeOrganizacion = URIRef('#id_de_organizacion', my_ns)
id_de_organizacion_tiene_tipo = URIRef('#id_de_organizacion_tiene_tipo', my_ns)
id_de_organizacion_tiene_literal = URIRef('#id_de_organizacion_tiene_literal', my_ns)
id_de_organizacion_tiene_organizacion = URIRef('#id_de_organizacion_tiene_organizacion', my_ns)
tiene_periodo_de_relacion_con_organizacion = URIRef('#tiene_periodo_de_relacion_con_organizacion', my_ns)
tiene_tipo_de_organizacion = URIRef('#tiene_tipo_de_organizacion', my_ns)
tiene_tipo_de_relacion_con_organizacion = URIRef('#tiene_tipo_de_relacion_con_organizacion', my_ns)
RelacionRepositorioYOrganizacion = URIRef('#relacion_repositorio_y_organizacion', my_ns)
relacion_repositorio_y_organizacion_tiene_repositorio = URIRef('#relacion_repositorio_y_organizacion_tiene_repositorio', my_ns)
relacion_repositorio_y_organizacion_tiene_organizacion = URIRef('#relacion_repositorio_y_organizacion_tiene_organizacion', my_ns)

ror_ns = Namespace('http://ror.org#')
