from rdflib import URIRef, Namespace
from config import DREPO_NS, CRITERIA_NS, ORGANIZATIONS_NS, LANGUAGE_NS

lang_ns = Namespace(LANGUAGE_NS)
lenguaje = URIRef("lenguaje", lang_ns)

my_ns = Namespace(DREPO_NS)

Pais = URIRef("pais", my_ns)
Locacion = URIRef("locacion", my_ns)

Organizacion = URIRef("organizacion", my_ns)
Repositorio = URIRef("repositorio", my_ns)
TipoDeIdDeOrganizacion = URIRef("tipo_de_id_de_organizacion", my_ns)
Disciplina = URIRef("disciplina", my_ns)
es_sub_disciplina_de = URIRef("es_sub_disciplina_de", my_ns)
esquema_de_disciplina = URIRef("esquema_de_disciplina", my_ns)
nombre_de_disciplina = URIRef("nombre_de_disciplina", my_ns)
MotorDeRepositorio = URIRef("motor_de_repositorio", my_ns)
Certificacion = URIRef("certificacion", my_ns)
utiliza_motor = URIRef('utiliza_motor', my_ns)
repositorio_afin_a_disciplina = URIRef('repositorio_afin_a_disciplina', my_ns)
tiene_nombre_organizacion = URIRef('tiene_nombre_organizacion', my_ns)
se_ubica_en = URIRef('se_ubica_en', my_ns)
incluido_en = URIRef('incluido_en', my_ns)
nombre_de_locacion = URIRef('nombre_de_locacion', my_ns)
alfa_3_de_pais = URIRef('alfa_3_de_pais', my_ns)
es_organizacion_padre = URIRef('es_organizacion_padre', my_ns) # ToDo: Make this relation Asymmetric e Irreflexiba?. Tb es_organizacion_antecesora?
es_organizacion_relacionada = URIRef('es_organizacion_relacionada', my_ns)
organizacion_esta_activa = URIRef('organizacion_esta_activa', my_ns)
organizacion_fundada_en_anio = URIRef('organizacion_fundada_en_anio', my_ns)
ApiParaCosecha = URIRef('api_para_cosecha', my_ns)
repositorio_aporta_funcionalidad = URIRef('repositorio_aporta_funcionalidad', my_ns)
ApiParaCosechaConUrl = URIRef('api_para_cosecha_con_url', my_ns)
api_para_cosecha_con_url_tiene_api_para_cosecha = URIRef('api_para_cosecha_con_url_tiene_api_para_cosecha', my_ns)
api_para_cosecha_con_url_tiene_url = URIRef('api_para_cosecha_con_url_tiene_url', my_ns)

EsquemaDeMetadatos = URIRef('esquema_de_metadatos', my_ns)
EsquemaDeIdDeAutor = URIRef('esquema_de_id_de_autor', my_ns)
EsquemaDeIdPersistente = URIRef('esquema_de_id_persistente', my_ns)
IntegracionConRedSocial = URIRef('integracion_con_red_social', my_ns)
Licencia = URIRef('licencia', my_ns)
Politica = URIRef('politica', my_ns)
TipoDeDato = URIRef('tipo_de_dato', my_ns)
ExportacionDeCitas = URIRef('exportacion_de_citas', my_ns)

tiene_url_repositorio = URIRef('tiene_url_repositorio', my_ns)
tiene_descripcion_repositorio = URIRef('tiene_descripcion_repositorio', my_ns)
tiene_nombre_repositorio = URIRef('tiene_nombre_repositorio', my_ns)
tiene_nombre_politica = URIRef('tiene_nombre_politica', my_ns)
tiene_url_politica = URIRef('tiene_url_politica', my_ns)
extiende_a_esquema_de_metadatos = URIRef('extiende_a_esquema_de_metadatos', my_ns)
extiende_a_esquema_de_id_persistente = URIRef('extiende_a_esquema_de_id_persistente', my_ns)

principles_ns = Namespace(CRITERIA_NS)
CriterioDeCalidad = URIRef("criterio_de_calidad", principles_ns)
GrupoDeCriterio = URIRef("grupo_de_criterio", principles_ns)
criterio_pertenece_a_grupo = URIRef("criterio_pertenece_a_grupo", principles_ns)
extiende_de_criterio = URIRef("extiende_de_criterio", principles_ns)
considera_criterio = URIRef("considera_criterio", principles_ns)
criterio_tiene_descripcion = URIRef("criterio_tiene_descripcion", principles_ns)

IdDeOrganizacion = URIRef('id_de_organizacion', my_ns)
id_de_organizacion_tiene_tipo = URIRef('id_de_organizacion_tiene_tipo', my_ns)
id_de_organizacion_tiene_literal = URIRef('id_de_organizacion_tiene_literal', my_ns)
id_de_organizacion_tiene_organizacion = URIRef('id_de_organizacion_tiene_organizacion', my_ns)
tiene_inicio_periodo_de_relacion_con_organizacion = URIRef('tiene_inicio_periodo_de_relacion_con_organizacion', my_ns)
tiene_fin_periodo_de_relacion_con_organizacion = URIRef('tiene_fin_periodo_de_relacion_con_organizacion', my_ns)
tiene_tipo_de_organizacion = URIRef('tiene_tipo_de_organizacion', my_ns)
tiene_tipo_de_relacion_con_organizacion = URIRef('tiene_tipo_de_relacion_con_organizacion', my_ns)
RelacionRepositorioYOrganizacion = URIRef('relacion_repositorio_y_organizacion', my_ns)
relacion_repositorio_y_organizacion_tiene_repositorio = URIRef('relacion_repositorio_y_organizacion_tiene_repositorio', my_ns)
relacion_repositorio_y_organizacion_tiene_organizacion = URIRef('relacion_repositorio_y_organizacion_tiene_organizacion', my_ns)

ror_ns = Namespace(ORGANIZATIONS_NS)
