from rdflib import Namespace

from onto.populator.ontology import onto_lenguajes, onto_tbox, onto_criterios
from onto.populator.utils import get_ref_from_ontology

lang_ns = Namespace(onto_lenguajes.base_iri)
my_ns = Namespace(onto_tbox.base_iri)
principles_ns = Namespace(onto_criterios.base_iri)
ror_ns = Namespace(onto_tbox.base_iri)

Pais = get_ref_from_ontology("pais")
Locacion = get_ref_from_ontology("locacion")

repositorio_creado_en_anio = get_ref_from_ontology("repositorio_creado_en_anio")
AplicacionDeCertificacionARepositorio = get_ref_from_ontology("aplicacion_de_certificacion_a_repositorio")
aplicacion_de_certificacion_a_repositorio_tiene_repositorio = get_ref_from_ontology("aplicacion_de_certificacion_a_repositorio_tiene_repositorio")
aplicacion_de_certificacion_a_repositorio_tiene_certificacion = get_ref_from_ontology("aplicacion_de_certificacion_a_repositorio_tiene_certificacion")
aplicacion_de_certificacion_a_repositorio_tiene_inicio_periodo = get_ref_from_ontology("aplicacion_de_certificacion_a_repositorio_tiene_inicio_periodo")
aplicacion_de_certificacion_a_repositorio_tiene_fin_periodo = get_ref_from_ontology("aplicacion_de_certificacion_a_repositorio_tiene_fin_periodo")

usa_lenguaje_repositorio = get_ref_from_ontology("usa_lenguaje_repositorio")

IdDeRepositorio = get_ref_from_ontology("id_de_repositorio")
id_de_repositorio_tiene_catalogo = get_ref_from_ontology("id_de_repositorio_tiene_catalogo")
id_de_repositorio_tiene_repositorio = get_ref_from_ontology("id_de_repositorio_tiene_repositorio")
id_de_repositorio_tiene_literal = get_ref_from_ontology("id_de_repositorio_tiene_literal")
CatalogoDeRepositorios = get_ref_from_ontology("catalogo_de_repositorios")
PalabraClave = get_ref_from_ontology("palabra_clave")
Organizacion = get_ref_from_ontology("organizacion")
Repositorio = get_ref_from_ontology("repositorio")
Rdd = get_ref_from_ontology("rdd")
Agregador = get_ref_from_ontology("agregador")
TipoDeIdDeOrganizacion = get_ref_from_ontology("tipo_de_id_de_organizacion")
Disciplina = get_ref_from_ontology("disciplina")
es_sub_disciplina_de = get_ref_from_ontology("es_sub_disciplina_de")
disciplina_tiene_esquema = get_ref_from_ontology("disciplina_tiene_esquema")
nombre_de_disciplina = get_ref_from_ontology("nombre_de_disciplina")
Software = get_ref_from_ontology("software")
Certificacion = get_ref_from_ontology("certificacion")
repositorio_asociado_a_software = get_ref_from_ontology('repositorio_asociado_a_software')
repositorio_afin_a_disciplina = get_ref_from_ontology('repositorio_afin_a_disciplina')
tiene_nombre_organizacion = get_ref_from_ontology('tiene_nombre_organizacion')
organizacion_se_ubica_en = get_ref_from_ontology('organizacion_se_ubica_en')
locacion_incluida_en = get_ref_from_ontology('locacion_incluida_en')
nombre_de_locacion = get_ref_from_ontology('nombre_de_locacion')
alfa_3_de_pais = get_ref_from_ontology('alfa_3_de_pais')
es_organizacion_padre = get_ref_from_ontology('es_organizacion_padre')
es_organizacion_relacionada = get_ref_from_ontology('es_organizacion_relacionada')
organizacion_esta_activa = get_ref_from_ontology('organizacion_esta_activa')
organizacion_fundada_en_anio = get_ref_from_ontology('organizacion_fundada_en_anio')
ProtocoloDeCosecha = get_ref_from_ontology('protocolo_de_cosecha')
repositorio_aporta_funcionalidad = get_ref_from_ontology('repositorio_aporta_funcionalidad')
# ApiParaCosechaConUrl = get_ref_from_ontology('api_para_cosecha_con_url')
# api_para_cosecha_con_url_tiene_api_para_cosecha = get_ref_from_ontology('api_para_cosecha_con_url_tiene_api_para_cosecha')
# api_para_cosecha_con_url_tiene_url = get_ref_from_ontology('api_para_cosecha_con_url_tiene_url')
tiene_sinonimo_palabra_clave = get_ref_from_ontology('tiene_sinonimo_palabra_clave')
tiene_palabra_clave_repositorio = get_ref_from_ontology('tiene_palabra_clave_repositorio')

EsquemaDeMetadatos = get_ref_from_ontology('esquema_de_metadatos')
EsquemaDeIdDeAutor = get_ref_from_ontology('esquema_de_id_de_autor')
EsquemaDeIdPersistente = get_ref_from_ontology('esquema_de_id_persistente')
RedSocial = get_ref_from_ontology('red_social')
Licencia = get_ref_from_ontology('licencia')
Politica = get_ref_from_ontology('politica')
TipoDeDato = get_ref_from_ontology('tipo_de_dato')
FormatoDeExportacionDeCitas = get_ref_from_ontology('formato_de_exportacion_de_citas')

tiene_nombre_licencia = get_ref_from_ontology('tiene_nombre_licencia')
tiene_url_licencia = get_ref_from_ontology('tiene_url_licencia')
repositorio_relacionado_con_licencia = get_ref_from_ontology('repositorio_relacionado_con_licencia')
repositorio_permite_licencia = get_ref_from_ontology('repositorio_permite_licencia')

repositorio_esta_activo = get_ref_from_ontology('repositorio_esta_activo')

tiene_url_repositorio = get_ref_from_ontology('tiene_url_repositorio')
tiene_descripcion_repositorio = get_ref_from_ontology('tiene_descripcion_repositorio')
tiene_nombre_repositorio = get_ref_from_ontology('tiene_nombre_repositorio')
tiene_nombre_politica = get_ref_from_ontology('tiene_nombre_politica')
tiene_url_politica = get_ref_from_ontology('tiene_url_politica')
extiende_a_esquema_de_metadatos = get_ref_from_ontology('extiende_a_esquema_de_metadatos')
extiende_a_esquema_de_id_persistente = get_ref_from_ontology('extiende_a_esquema_de_id_persistente')

CriterioDeCalidad = get_ref_from_ontology("criterio_de_calidad")
GrupoDeCriterio = get_ref_from_ontology("grupo_de_criterio")
criterio_pertenece_a_grupo = get_ref_from_ontology("criterio_pertenece_a_grupo")
extiende_de_criterio = get_ref_from_ontology("extiende_de_criterio")
considera_criterio = get_ref_from_ontology("considera_criterio")
criterio_tiene_descripcion = get_ref_from_ontology("criterio_tiene_descripcion")

IdDeOrganizacion = get_ref_from_ontology('id_de_organizacion')
id_de_organizacion_tiene_tipo = get_ref_from_ontology('id_de_organizacion_tiene_tipo')
id_de_organizacion_tiene_literal = get_ref_from_ontology('id_de_organizacion_tiene_literal')
id_de_organizacion_tiene_organizacion = get_ref_from_ontology('id_de_organizacion_tiene_organizacion')
tiene_inicio_periodo_de_relacion_con_organizacion = get_ref_from_ontology('tiene_inicio_periodo_de_relacion_con_organizacion')
tiene_fin_periodo_de_relacion_con_organizacion = get_ref_from_ontology('tiene_fin_periodo_de_relacion_con_organizacion')
tiene_tipo_de_organizacion = get_ref_from_ontology('tiene_tipo_de_organizacion')
tiene_tipo_de_relacion_con_organizacion = get_ref_from_ontology('tiene_tipo_de_relacion_con_organizacion')
RelacionRepositorioYOrganizacion = get_ref_from_ontology('relacion_repositorio_y_organizacion')
relacion_repositorio_y_organizacion_tiene_repositorio = get_ref_from_ontology('relacion_repositorio_y_organizacion_tiene_repositorio')
relacion_repositorio_y_organizacion_tiene_organizacion = get_ref_from_ontology('relacion_repositorio_y_organizacion_tiene_organizacion')

FormatoDeArchivo = get_ref_from_ontology('formato_de_archivo')
FormatoDeArchivoAbierto = get_ref_from_ontology('formato_de_archivo_abierto')
