
# ToDo: Ponerle un "esquema de disciplina" o la posibilidad de especificar el vocabulario controlado de la disciplina
dfg_subjects = [
    ('1', 'Humanities and Social Sciences', [
        ('11', 'Humanities', [
            ('101', 'Ancient Cultures', [
                ('10101', 'Prehistory and World Archaeology'),
                ('10102', 'Classical Philology'),
                ('10103', 'Ancient History'),
                ('10104', 'Classical Archaeology'),
                ('10105', 'Egyptology and Ancient Near Eastern Studies'),
            ]),
            ('102', 'History', [
                ('10201', 'Medieval History'),
                ('10202', 'Early Modern History'),
                ('10203', 'Modern and Current History'),
                ('10204', 'History of Science'),
            ]),
            ('103', 'Art History, Music, Theatre and Media Studies', [
                ('10301', 'Art History'),
                ('10302', 'Musicology'),
                ('10303', 'Theatre and Media Studies'),
            ]),
            ('104', 'Linguistics', [
                ('10401', 'General and Comparative Linguistics, Typology, Non-European Languages'),
                ('10402', 'Individual Linguistics'),
                ('10403', 'Historical Linguistics'),
                ('10404', 'Applied Linguistics, Experimental Linguistics, Computational Linguistics'),
            ]),
            ('105', 'Literary Studies', [
                ('10501', 'Medieval German Literature'),
                ('10502', 'Modern German Literature'),
                ('10503', 'European and American Literature'),
                ('10504', 'General and Comparative Literature and Cultural Studies'),
            ]),
            ('106', 'Social and Cultural Anthropology, Non-European Cultures, Jewish Studies and Religious Studies', [
                ('10601', 'Social and Cultural Anthropology and Ethnology'),
                ('10602', 'Asian Studies'),
                ('10603', 'African, American and Oceania Studies'),
                ('10604', 'Islamic Studies, Arabian Studies, Semitic Studies'),
                ('10605', 'Religious Studies and Jewish Studies'),
            ]),
            ('107', 'Theology', [
                ('10701', 'Protestant Theology'),
                ('10702', 'Roman Catholic Theology'),
            ]),
            ('108', 'Philosophy', [
                ('10801', 'History of Philosophy'),
                ('10802', 'Theoretical Philosophy'),
                ('10803', 'Practical Philosophy'),
            ]),
        ]),
        ('12', 'Social and Behavioural Sciences', [
            ('109', 'Educational Research', [
                ('10901', 'General Education and History of Education'),
                ('10902', 'General and Domain-Specific Teaching and Learning'),
                ('10903', 'Education Systems and Educational Institutions'),
                ('10904', 'Educational Research on Socialisation, Welfare and Professionalism Research'),
            ]),
            ('110', 'Psychology', [
                ('11001', 'General, Cognitive and Mathematical Psychology'),
                ('11002', 'Biological Psychology and Cognitive Neuroscience'),
                ('11003', 'Developmental and Educational Psychology'),
                ('11004', 'Social Psychology, Industrial and Organisational Psychology'),
                ('11005', 'Differential, Clinical and Medical Psychology, Methodology'),
            ]),
            ('111', 'Social Sciences', [
                ('11101', 'Sociological Theory'),
                ('11102', 'Empirical Social Research'),
                ('11103', 'Communication Sciences'),
                ('11104', 'Political Science'),
            ]),
            ('112', 'Economics', [
                ('11201', 'Economic Theory'),
                ('11202', 'Economic Policy, Applied Economics'),
                ('11203', 'Business Administration'),
                ('11204', 'Statistics and Econometrics'),
                ('11205', 'Economic and Social History'),
            ]),
            ('113', 'Jurisprudence', [
                ('11301', 'Principles of Law and Jurisprudence'),
                ('11302', 'Private Law'),
                ('11303', 'Public Law'),
                ('11304', 'Criminal Law'),
                ('11305', 'Criminology'),
            ]),
        ]),
    ]),
    ('2', 'Life Sciences', [
        ('21', 'Biology', [
            ('201', 'Basic Research in Biology and Medicine', [
                ('20101', 'Biochemistry'),
                ('20102', 'Biophysics'),
                ('20103', 'Cell Biology'),
                ('20104', 'Structural Biology'),
                ('20105', 'General Genetics and Functional Genome Biology'),
                ('20106', 'Developmental Biology'),
                ('20107', 'Bioinformatics and Theoretical Biology'),
            ]),
            ('202', 'Plant Sciences', [
                ('20201', 'Evolution and Systematics of Plants and Fungi'),
                ('20202', 'Ecology and Biodiversity of Plants and Ecosystems'),
                ('20203', 'Organismic Interactions, Chemical Ecology and Microbiomes of Plant Systems'),
                ('20204', 'Plant Physiology'),
                ('20205', 'Plant Biochemistry and Biophysics'),
                ('20206', 'Plant Cell and Developmental Biology'),
                ('20207', 'Plant Genetics'),
            ]),
            ('203', 'Zoology', [
                ('20301', 'Systematics and Morphology (Zoology)'),
                ('20302', 'Evolution, Anthropology'),
                ('20303', 'Ecology and Biodiversity of Animals and Ecosystems, Organismic Interactions'),
                ('20304', 'Sensory and Behavioural Biology'),
                ('20305', 'Animal Physiology and Biochemistry'),
                ('20306', 'Evolutionary Cell and Developmental Biology (Zoology)'),
            ]),
        ]),
        ('22', 'Medicine', [
            ('204', 'Microbiology, Virology and Immunology', [
                ('20401', 'Metabolism, Biochemistry and Genetics of Microorganisms'),
                ('20402', 'Microbial Ecology and Applied Microbiology'),
                ('20403', 'Medical Microbiology and Mycology, Hygiene, Molecular Infection Biology'),
                ('20404', 'Virology'),
                ('20405', 'Immunology'),
                ('20406', 'Parasitology and Biology of Tropical Infectious Disease Pathogens'),
            ]),
            ('205', 'Medicine', [
                ('20501', 'Epidemiology and Medical Biometry/Statistics'),
                ('20502', 'Public Health, Health Services Research, Social Medicine'),
                ('20503', 'Human Genetics'),
                ('20504', 'Physiology'),
                ('20505', 'Nutritional Sciences'),
                ('20506', 'Pathology'),
                ('20507', 'Medical Informatics and Medical Bioinformatics'),
                ('20508', 'Pharmacy'),
                ('20509', 'Pharmacology'),
                ('20510', 'Toxicology, Occupational Medicine, Clinical Chemistry'),
                ('20511', 'Anaesthesiology'),
                ('20512', 'Cardiology, Angiology'),
                ('20513', 'Pneumology, Thoracic Surgery'),
                ('20514', 'Hematology, Oncology'),
                ('20515', 'Gastroenterology'),
                ('20516', 'Nephrology'),
                ('20517', 'Endocrinology, Diabetology, Metabolism'),
                ('20518', 'Rheumatology'),
                ('20519', 'Dermatology'),
                ('20520', 'Pediatric and Adolescent Medicine'),
                ('20521', 'Gynaecology and Obstetrics'),
                ('20522', 'Clinical Immunology and Allergology'),
                ('20523', 'Reproductive Medicine, Urology'),
                ('20524', 'Biogerontology and Geriatric Medicine'),
                ('20525', 'General and Visceral Surgery'),
                ('20526', 'Cardiac and Vascular Surgery'),
                ('20527', 'Orthopaedics, Traumatology, Reconstructive Surgery'),
                ('20528', 'Dentistry, Oral Surgery'),
                ('20529', 'Otolaryngology'),
                ('20530', 'Radiology, Nuclear Medicine, Radiotherapy, Radiobiology'),
                ('20531', 'Clinical Infectiology and Tropical Medicine'),
                ('20532', 'Medical Physics, Biomedical Technology'),
                ('20533', 'Anatomy'),
            ]),
            ('206', 'Neurosciences', [
                ('20601', 'Developmental Neurobiology'),
                ('20602', 'Molecular Biology and Physiology of Neurons and Glial Cells'),
                ('20603', 'Experimental and Theoretical Network Neuroscience'),
                ('20604', 'Cognitive, Systems and Behavioural Neurobiology'),
                ('20605', 'Experimental Models for the Understanding of Nervous System Diseases'),
                ('20606', 'Molecular and Cellular Neurology and Neuropathology'),
                ('20607', 'Clinical Neurology; Neurosurgery and Neuroradiology'),
                ('20608', 'Human Cognitive and Systems Neuroscience'),
                ('20609', 'Biological Psychiatry'),
                ('20610', 'Clinical Psychiatry, Psychotherapy, Child and Adolescent Psychiatry'),
                ('20611', 'Ophthalmology'),
            ]),
        ]),
        ('23', 'Agriculture, Forestry and Veterinary Medicine', [
            ('207', 'Agriculture, Forestry and Veterinary Medicine', [
                ('20701', 'Soil Sciences'),
                ('20702', 'Plant Breeding and Plant Pathology'),
                ('20703', 'Plant Cultivation, Plant Nutrition, Agricultural Technology'),
                ('20704', 'Ecology of Land Use'),
                ('20705', 'Agricultural Economics, Agricultural Policy, Agricultural Sociology'),
                ('20706', 'Forestry'),
                ('20707', 'Animal Breeding, Animal Nutrition, Animal Husbandry'),
                ('20708', 'Veterinary Medical Science'),
            ]),
        ]),
    ]),
    ('3', 'Natural Sciences', [
        ('31', 'Physics', [
            ('307', 'Condensed Matter Physics', [
                ('30701', 'Experimental Condensed Matter Physics'),
                ('30702', 'Theoretical Condensed Matter Physics'),
            ]),
            ('308', 'Optics, Quantum Optics and Physics of Atoms, Molecules and Plasmas', [
                ('30801', 'Optics, Quantum Optics, Atoms, Molecules, Plasmas'),
            ]),
            ('309', 'Particles, Nuclei and Fields', [
                ('30901', 'Nuclear and Elementary Particle Physics, Quantum Mechanics, Relativity, Fields'),
            ]),
            ('310', 'Statistical Physics, Soft Matter, Biological Physics, Nonlinear Dynamics', [
                ('31001', 'Statistical Physics, Soft Matter, Biological Physics, Nonlinear Dynamics'),
            ]),
            ('311', 'Astrophysics and Astronomy', [
                ('31101', 'Astrophysics and Astronomy'),
            ]),
        ]),
        ('32', 'Mathematics', [
            ('312', 'Mathematics', [
                ('31201', 'Mathematics'),
            ]),
        ]),
        ('33', 'Geosciences (including Geography)', [
            ('313', 'Atmospheric Science, Oceanography and Climate Research', [
                ('31301', 'Atmospheric Science'),
                ('31302', 'Oceanography'),
            ]),
            ('314', 'Geology and Palaeontology', [
                ('31401', 'Geology and Palaeontology'),
            ]),
            ('315', 'Geophysics and Geodesy', [
                ('31501', 'Geophysics'),
                ('31502', 'Geodesy, Photogrammetry, Remote Sensing, Geoinformatics, Cartography'),
            ]),
            ('316', 'Mineralogy, Petrology and Geochemistry', [
                ('31601', 'Mineralogy, Petrology and Geochemistry'),
            ]),
            ('317', 'Geography', [
                ('31701', 'Physical Geography'),
                ('31702', 'Human Geography'),
            ]),
            ('318', 'Water Research', [
                ('31801',
                 'Hydrogeology, Hydrology, Limnology, Urban Water Management, Water Chemistry, Integrated Water Resources Management'),
            ]),
        ]),
        ('34', 'Chemistry', [
            ('321', 'Molecular Chemistry', [
                ('32101', 'Inorganic Molecular Chemistry - Synthesis and Characterisation'),
                ('32102', 'Organic Molecular Chemistry - Synthesis and Characterisation'),
            ]),
            ('322', 'Chemical Solid State and Surface Research', [
                ('32201', 'Solid State and Surface Chemistry, Material Synthesis'),
                ('32202', 'Physical Chemistry of Solids and Surfaces, Material Characterisation'),
            ]),
            ('323', 'Physical Chemistry', [
                ('32301', 'Physical Chemistry of Molecules, Liquids and Interfaces, Biophysical Chemistry'),
            ]),
            ('324', 'Analytical Chemistry', [
                ('32401', 'Analytical Chemistry'),
            ]),
            ('325', 'Biological Chemistry and Food Chemistry', [
                ('32501', 'Biological and Biomimetic Chemistry'),
                ('32502', 'Food Chemistry'),
            ]),
            ('326', 'Polymer Research', [
                ('32601', 'Preparatory and Physical Chemistry of Polymers'),
                ('32602', 'Experimental and Theoretical Physics of Polymers'),
                ('32603', 'Polymer Materials'),
            ]),
            ('327', 'Theoretical Chemistry', [
                ('32701', 'Theoretical Chemistry: Electron Structure, Dynamics, Simulation'),
                ('32702', 'Theoretical Chemistry: Molecules, Materials, Surfaces'),
            ]),
        ]),
    ]),
    ('4', 'Engineering Sciences', [
        ('41', 'Mechanical and industrial Engineering', [
            ('401', 'Production Technology', [
                ('40101', 'Metal-Cutting and Abrasive Manufacturing Engineering'),
                ('40102', 'Primary Shaping and Reshaping Technology, Additive Manufacturing'),
                ('40103', 'Joining and Separation Technology'),
                ('40104', 'Plastics Engineering'),
                ('40105', 'Production Systems, Operations Management, Quality Management and Factory Planning'),
                ('40106', 'Production Automation'),
            ]),
            ('402', 'Mechanics and Constructive Mechanical Engineering', [
                ('40201', 'Engineering Design, Machine Elements, Product Development'),
                ('40202', 'Mechanics'),
                ('40203', 'Lightweight Construction, Textile Technology'),
                ('40204', 'Acoustics'),
            ]),
        ]),
        ('42', 'Thermal Engineering/Process Engineering', [
            ('403', 'Process Engineering, Technical Chemistry', [
                ('40301', 'Chemical and Thermal Process Engineering'),
                ('40302', 'Technical Chemistry'),
                ('40303', 'Mechanical Process Engineering'),
                ('40304', 'Biological Process Engineering'),
            ]),
            ('404', 'Fluid Mechanics, Technical Thermodynamics and Thermal Energy Engineering', [
                ('40401', 'Energy Process Engineering'),
                ('40402', 'Technical Thermodynamics'),
                ('40403', 'Fluid Mechanics'),
                ('40404', 'Hydraulic and Turbo Engines and Piston Engines'),
            ]),
        ]),
        ('43', 'Materials Science and Engineering', [
            ('405', 'Materials Engineering', [
                ('40501', 'Metallurgical, Thermal and Thermomechanical Treatment of Materials'),
                ('40502', 'Materials in Sintering Processes and Generative Manufacturing Processes'),
                ('40503', 'Coating and Surface Technology'),
                ('40504', 'Mechanical Properties of Metallic Materials and their Microstructural Origins'),
                ('40505', 'Glass, Ceramics and Derived Composites'),
                ('40506', 'Polymeric and Biogenic Materials and Derived Composites'),
            ]),
            ('406', 'Materials Science', [
                ('40601', 'Synthesis and Properties of Functional Materials'),
                ('40602', 'Biomaterials'),
                ('40603', 'Thermodynamics and Kinetics as well as Properties of Phases and Microstructure of Materials'),
                ('40604',
                 'Computer-Aided Design of Materials and Simulation of Materials Behaviour from Atomic to Microscopic Scale'),
            ]),
        ]),
        ('44', 'Computer Science, Electrical and System Engineering', [
            ('407', 'Systems Engineering', [
                ('40701', 'Automation, Control Systems, Robotics, Mechatronics, Cyber Physical Systems'),
                ('40702', 'Measurement Systems'),
                ('40703', 'Microsystems'),
                ('40704', 'Traffic and Transport Systems, Intelligent and Automated Traffic'),
                ('40705', 'Human Factors, Ergonomics, Human-Machine Systems'),
                ('40706', 'Biomedical Systems Technology'),
            ]),
            ('408', 'Electrical Engineering and Information Technology', [
                ('40801', 'Electronic Semiconductors, Components, Circuits, Systems'),
                ('40802', 'Communications, High-Frequency and Network Technology, Theoretical Electrical Engineering'),
                ('40803', 'Electrical Energy Generation, Distribution, Application'),
            ]),
            ('409', 'Computer Science', [
                ('40901', 'Theoretical Computer Science'),
                ('40902', 'Software Engineering and Programming Languages'),
                ('40903', 'Security and Dependability'),
                ('40904', 'Operating, Communication, Database and Distributed Systems'),
                ('40905',
                 'Interactive and Intelligent Systems, Image and Language Processing, Computer Graphics and Visualisation'),
                ('40906', 'Information Systems, Process and Knowledge Management'),
                ('40907', 'Computer Architecture and Embedded Systems'),
                ('40908', 'Massively Parallel and Data-Intensive Systems'),
            ]),
        ]),
        ('45', 'Construction Engineering and Architecture', [
            ('410', 'Construction Engineering and Architecture', [
                ('41001',
                 'Architecture, Building and Construction History, Construction Research, Sustainable Building Technology'),
                ('41002', 'Urbanism, Spatial Planning, Transportation and Infrastructure Planning, Landscape Planning'),
                ('41003', 'Construction Material Sciences, Chemistry, Building Physics'),
                ('41004', 'Structural Engineering, Building Informatics and Construction Operation'),
                ('41005', 'Applied Mechanics, Statics and Dynamics'),
                ('41006', 'Geotechnics, Hydraulic Engineering'),
            ]),
        ]),
    ]),
]

coar_content_types = list(map(lambda x: (x[0], "http://purl.org/coar/resource_type/%s" % (x[1], )), [
    ('dataset', 'c_ddb1'),
    ('aggregated data', 'ACF7-8YT9'),
    ('clinical trial data', 'c_cb28'),
    ('compiled data', 'FXF3-D3G7'),
    ('encoded data', 'AM6W-6QAW'),
    ('experimental data', '63NG-B465'),
    ('genomic data', 'A8F1-NPV9'),
    ('geospatial data', '2H0M-X761'),
    ('laboratory notebook', 'H41Y-FW7B'),
    ('measurement and test data', 'DD58-GFSX'),
    ('observational data', 'FF4C-28RK'),
    ('recorded data', 'CQMR-7K63'),
    ('simulation data', 'W2XT-7017'),
    ('survey data', 'NHD0-W6SY'),
    ('image', 'c_c513'),
    ('moving image', 'c_8a7e'),
    ('still image', 'c_ecc8'),
    ('software', 'c_5ce6'),
    ('research software', 'c_c950'),
    ('source code', 'QH80-2R4E'),
    ('text', 'c_18cf'),
    ('other', 'c_1843'),
]))

languages = [
    ('deu', 'German'),
    ('eng', 'English'),
    ('fra', 'French'),
    ('aar', 'Afar'),
    ('abk', 'Abkhaz'),
    ('afr', 'Afrikaans'),
    ('aka', 'Akan'),
    ('amh', 'Amharic'),
    ('ara', 'Arabic'),
    ('arg', 'Aragonese'),
    ('asm', 'Assamese'),
    ('ava', 'Avaric'),
    ('ave', 'Avestan'),
    ('aym', 'Aymara'),
    ('aze', 'Azerbaijani'),
    ('bak', 'Bashkir'),
    ('bam', 'Bambara'),
    ('bel', 'Belarusian'),
    ('ben', 'Bengali'),
    ('bis', 'Bislama'),
    ('bod', 'Tibetan Standard, Tibetan, Central'),
    ('bos', 'Bosnian'),
    ('bre', 'Breton'),
    ('bul', 'Bulgarian'),
    ('cat', 'Catalan; Valencian'),
    ('ces', 'Czech'),
    ('cha', 'Chamorro'),
    ('che', 'Chechen'),
    ('chu', 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic'),
    ('chv', 'Chuvash'),
    ('cor', 'Cornish'),
    ('cos', 'Corsican'),
    ('cre', 'Cree'),
    ('cym', 'Welsh'),
    ('dan', 'Danish'),
    ('div', 'Divehi; Dhivehi; Maldivian;'),
    ('dzo', 'Dzongkha'),
    ('ell', 'Greek, Modern'),
    ('epo', 'Esperanto'),
    ('est', 'Estonian'),
    ('eus', 'Basque'),
    ('ewe', 'Ewe'),
    ('fao', 'Faroese'),
    ('fas', 'Persian'),
    ('fij', 'Fijian'),
    ('fin', 'Finnish'),
    ('fry', 'Western Frisian'),
    ('ful', 'Fula; Fulah; Pulaar; Pular'),
    ('gla', 'Scottish Gaelic; Gaelic'),
    ('gle', 'Irish'),
    ('glg', 'Galician'),
    ('glv', 'Manx'),
    ('grn', 'Guarani'),
    ('guj', 'Gujarati'),
    ('hat', 'Haitian; Haitian Creole'),
    ('hau', 'Hausa'),
    ('heb', 'Hebrew (modern)'),
    ('her', 'Herero'),
    ('hin', 'Hindi'),
    ('hmo', 'Hiri Motu'),
    ('hrv', 'Croatian'),
    ('hun', 'Hungarian'),
    ('hye', 'Armenian'),
    ('ibo', 'Igbo'),
    ('ido', 'Ido'),
    ('iii', 'Nuosu'),
    ('iku', 'Inuktitut'),
    ('ile', 'Interlingue'),
    ('ina', 'Interlingua'),
    ('ind', 'Indonesian'),
    ('ipk', 'Inupiaq'),
    ('isl', 'Icelandic'),
    ('ita', 'Italian'),
    ('jav', 'Javanese'),
    ('jpn', 'Japanese'),
    ('kal', 'Kalaallisut, Greenlandic'),
    ('kan', 'Kannada'),
    ('kas', 'Kashmiri'),
    ('kat', 'Georgian'),
    ('kau', 'Kanuri'),
    ('kaz', 'Kazakh'),
    ('khm', 'Khmer'),
    ('kik', 'Kikuyu, Gikuyu'),
    ('kin', 'Kinyarwanda'),
    ('kir', 'Kyrgyz'),
    ('kom', 'Komi'),
    ('kon', 'Kongo'),
    ('kor', 'Korean'),
    ('kua', 'Kwanyama, Kuanyama'),
    ('kur', 'Kurdish'),
    ('lao', 'Lao'),
    ('lat', 'Latin'),
    ('lav', 'Latvian'),
    ('lim', 'Limburgish, Limburgan, Limburger'),
    ('lin', 'Lingala'),
    ('lit', 'Lithuanian'),
    ('ltz', 'Luxembourgish, Letzeburgesch'),
    ('lub', 'Luba-Katanga'),
    ('lug', 'Ganda'),
    ('mah', 'Marshallese'),
    ('mal', 'Malayalam'),
    ('mar', 'Marathi'),
    ('mkd', 'Macedonian'),
    ('mlg', 'Malagasy'),
    ('mlt', 'Maltese'),
    ('mon', 'Mongolian'),
    ('mri', 'Maori'),
    ('msa', 'Malay'),
    ('mya', 'Burmese'),
    ('nau', 'Nauru'),
    ('nav', 'Navajo, Navaho'),
    ('nbl', 'South Ndebele'),
    ('nde', 'North Ndebele'),
    ('ndo', 'Ndonga'),
    ('nep', 'Nepali'),
    ('nld', 'Dutch'),
    ('nno', 'Norwegian Nynorsk'),
    ('nob', 'Norwegian Bokmal'),
    ('nor', 'Norwegian'),
    ('nya', 'Chichewa; Chewa; Nyanja'),
    ('oci', 'Occitan'),
    ('oji', 'Ojibwe, Ojibwa'),
    ('ori', 'Oriya'),
    ('orm', 'Oromo'),
    ('oss', 'Ossetian, Ossetic'),
    ('pan', 'Panjabi, Punjabi'),
    ('pli', 'Pali'),
    ('pol', 'Polish'),
    ('por', 'Portuguese'),
    ('pus', 'Pashto, Pushto'),
    ('que', 'Quechua'),
    ('roh', 'Romansh'),
    ('ron', 'Romanian, Moldavian(Romanian from Republic of Moldova)'),
    ('run', 'Kirundi'),
    ('rus', 'Russian'),
    ('sag', 'Sango'),
    ('san', 'Sanskrit (Samskrta)'),
    ('sin', 'Sinhala, Sinhalese'),
    ('slk', 'Slovak'),
    ('slv', 'Slovene'),
    ('sme', 'Northern Sami'),
    ('smo', 'Samoan'),
    ('sna', 'Shona'),
    ('snd', 'Sindhi'),
    ('som', 'Somali'),
    ('sot', 'Southern Sotho'),
    ('spa', 'Spanish; Castilian'),
    ('sqi', 'Albanian'),
    ('srd', 'Sardinian'),
    ('srp', 'Serbian'),
    ('ssw', 'Swati'),
    ('sun', 'Sundanese'),
    ('swa', 'Swahili'),
    ('swe', 'Swedish'),
    ('tah', 'Tahitian'),
    ('tam', 'Tamil'),
    ('tat', 'Tatar'),
    ('tel', 'Telugu'),
    ('tgk', 'Tajik'),
    ('tgl', 'Tagalog'),
    ('tha', 'Thai'),
    ('tir', 'Tigrinya'),
    ('ton', 'Tonga (Tonga Islands)'),
    ('tsn', 'Tswana'),
    ('tso', 'Tsonga'),
    ('tuk', 'Turkmen'),
    ('tur', 'Turkish'),
    ('twi', 'Twi'),
    ('uig', 'Uighur, Uyghur'),
    ('ukr', 'Ukrainian'),
    ('urd', 'Urdu'),
    ('uzb', 'Uzbek'),
    ('ven', 'Venda'),
    ('vie', 'Vietnamese'),
    ('vol', 'Volapuk'),
    ('wln', 'Walloon'),
    ('wol', 'Wolof'),
    ('xho', 'Xhosa'),
    ('yid', 'Yiddish'),
    ('yor', 'Yoruba'),
    ('zha', 'Zhuang, Chuang'),
    ('zho', 'Chinese'),
    ('zul', 'Zulu'),
]

countries = [
    # ('EEC', 'European Union'), # ToDo: Ojo con ésto que codifica varios países
    # ('AAA', 'International'), # ToDo: Ojo con ésto que codifica varios países
    ('EU', 'European Union', [
        ('BEL', 'Belgium'),
        ('BGR', 'Bulgaria'),
        ('CZE', 'Czechia'),
        ('AUT', 'Austria'),
        ('HRV', 'Croatia'),
        ('CYP', 'Cyprus'),
        ('DNK', 'Denmark'),
        ('EST', 'Estonia'),
        ('FIN', 'Finland'),
        ('PRT', 'Portugal'),
        ('NLD', 'Netherlands'),
        ('LTU', 'Lithuania'),
        ('LUX', 'Luxembourg'),
        ('DEU', 'Germany'),
        ('ESP', 'Spain'),
        ('FRA', 'France'),
        ('GRC', 'Greece'),
        ('HUN', 'Hungary'),
        ('IRL', 'Ireland'),
        ('SWE', 'Sweden'),
        ('SVK', 'Slovakia'),
        ('SVN', 'Slovenia'),
        ('ITA', 'Italy'),
        ('ROU', 'Romania'),
        ('LVA', 'Latvia'),
        ('MLT', 'Malta'),
        ('POL', 'Poland'),
    ]),
    ('ABW', 'Aruba'),
    ('AFG', 'Afghanistan'),
    ('AGO', 'Angola'),
    ('AIA', 'Anguilla'),
    ('ALA', 'Aland Islands'),
    ('ALB', 'Albania'),
    ('AND', 'Andorra'),
    ('ARE', 'United Arab Emirates'),
    ('ARG', 'Argentina'),
    ('ARM', 'Armenia'),
    ('ASM', 'American Samoa'),
    ('ATA', 'Antarctica'),
    ('ATF', 'French Southern Territories'),
    ('ATG', 'Antigua and Barbuda'),
    ('AUS', 'Australia'),
    ('AZE', 'Azerbaijan'),
    ('BDI', 'Burundi'),
    ('BEN', 'Benin'),
    ('BES', 'Bonaire, Sint Eustatius and Saba'),
    ('BFA', 'Burkina Faso'),
    ('BGD', 'Bangladesh'),
    ('BHR', 'Bahrain'),
    ('BHS', 'Bahamas'),
    ('BIH', 'Bosnia and Herzegovina'),
    ('BLM', 'Saint Barthelemy'),
    ('BLR', 'Belarus'),
    ('BLZ', 'Belize'),
    ('BMU', 'Bermuda'),
    ('BOL', 'Bolivia, Plurinational State of'),
    ('BRA', 'Brazil'),
    ('BRB', 'Barbados'),
    ('BRN', 'Brunei Darussalam'),
    ('BTN', 'Bhutan'),
    ('BVT', 'Bouvet Island'),
    ('BWA', 'Botswana'),
    ('CAF', 'Central African Republic'),
    ('CAN', 'Canada'),
    ('CCK', 'Cocos (Keeling) Islands'),
    ('CHE', 'Switzerland'),
    ('CHL', 'Chile'),
    ('CHN', 'China'),
    ('CIV', 'Cote d\'Ivoire'),
    ('CMR', 'Cameroon'),
    ('COD', 'Congo, the Democratic Republic of the'),
    ('COG', 'Congo'),
    ('COK', 'Cook Islands'),
    ('COL', 'Colombia'),
    ('COM', 'Comoros'),
    ('CPV', 'Cabo Verde'),
    ('CRI', 'Costa Rica'),
    ('CUB', 'Cuba'),
    ('CUW', 'Curacao'),
    ('CXR', 'Christmas Island'),
    ('CYM', 'Cayman Islands'),
    ('DJI', 'Djibouti'),
    ('DMA', 'Dominica'),
    ('DOM', 'Dominican Republic'),
    ('DZA', 'Algeria'),
    ('ECU', 'Ecuador'),
    ('EGY', 'Egypt'),
    ('ERI', 'Eritrea'),
    ('ESH', 'Western Sahara'),
    ('ETH', 'Ethiopia'),
    ('FJI', 'Fiji'),
    ('FLK', 'Falkland Islands (Malvinas)'),
    ('FRO', 'Faroe Islands'),
    ('FSM', 'Micronesia, Federated States of'),
    ('GAB', 'Gabon'),
    ('GBR', 'United Kingdom'),
    ('GEO', 'Georgia'),
    ('GGY', 'Guernsey'),
    ('GHA', 'Ghana'),
    ('GIB', 'Gibraltar'),
    ('GIN', 'Guinea'),
    ('GLP', 'Guadeloupe'),
    ('GMB', 'Gambia'),
    ('GNB', 'Guinea-Bissau'),
    ('GNQ', 'Equatorial Guinea'),
    ('GRD', 'Grenada'),
    ('GRL', 'Greenland'),
    ('GTM', 'Guatemala'),
    ('GUF', 'French Guiana'),
    ('GUM', 'Guam'),
    ('GUY', 'Guyana'),
    ('HKG', 'Hong Kong'),
    ('HMD', 'Heard Island and McDonald Islands'),
    ('HND', 'Honduras'),
    ('HTI', 'Haiti'),
    ('IDN', 'Indonesia'),
    ('IMN', 'Isle of Man'),
    ('IND', 'India'),
    ('IOT', 'British Indian Ocean Territory'),
    ('IRN', 'Iran, Islamic Republic of'),
    ('IRQ', 'Iraq'),
    ('ISL', 'Iceland'),
    ('ISR', 'Israel'),
    ('JAM', 'Jamaica'),
    ('JEY', 'Jersey'),
    ('JOR', 'Jordan'),
    ('JPN', 'Japan'),
    ('KAZ', 'Kazakhstan'),
    ('KEN', 'Kenya'),
    ('KGZ', 'Kyrgyzstan'),
    ('KHM', 'Cambodia'),
    ('KIR', 'Kiribati'),
    ('KNA', 'Saint Kitts and Nevis'),
    ('KOR', 'Korea, Republic of'),
    ('KWT', 'Kuwait'),
    ('LAO', 'Lao People\'s Democratic Republic'),
    ('LBN', 'Lebanon'),
    ('LBR', 'Liberia'),
    ('LBY', 'Libya'),
    ('LCA', 'Saint Lucia'),
    ('LIE', 'Liechtenstein'),
    ('LKA', 'Sri Lanka'),
    ('LSO', 'Lesotho'),
    ('MAC', 'Macao'),
    ('MAF', 'Saint Martin (French part)'),
    ('MAR', 'Morocco'),
    ('MCO', 'Monaco'),
    ('MDA', 'Moldova, Republic of'),
    ('MDG', 'Madagascar'),
    ('MDV', 'Maldives'),
    ('MEX', 'Mexico'),
    ('MHL', 'Marshall Islands'),
    ('MKD', 'North Macedonia'),
    ('MLI', 'Mali'),
    ('MMR', 'Myanmar'),
    ('MNE', 'Montenegro'),
    ('MNG', 'Mongolia'),
    ('MNP', 'Northern Mariana Islands'),
    ('MOZ', 'Mozambique'),
    ('MRT', 'Mauritania'),
    ('MSR', 'Montserrat'),
    ('MTQ', 'Martinique'),
    ('MUS', 'Mauritius'),
    ('MWI', 'Malawi'),
    ('MYS', 'Malaysia'),
    ('MYT', 'Mayotte'),
    ('NAM', 'Namibia'),
    ('NCL', 'New Caledonia'),
    ('NER', 'Niger'),
    ('NFK', 'Norfolk Island'),
    ('NGA', 'Nigeria'),
    ('NIC', 'Nicaragua'),
    ('NIU', 'Niue'),
    ('NOR', 'Norway'),
    ('NPL', 'Nepal'),
    ('NRU', 'Nauru'),
    ('NZL', 'New Zealand'),
    ('OMN', 'Oman'),
    ('PAK', 'Pakistan'),
    ('PAN', 'Panama'),
    ('PCN', 'Pitcairn'),
    ('PER', 'Peru'),
    ('PHL', 'Philippines'),
    ('PLW', 'Palau'),
    ('PNG', 'Papua New Guinea'),
    ('PRI', 'Puerto Rico'),
    ('PRK', 'Korea, Democratic People\'s Republic of'),
    ('PRY', 'Paraguay'),
    ('PSE', 'Palestinian Territory, Occupied'),
    ('PYF', 'French Polynesia'),
    ('QAT', 'Qatar'),
    ('REU', 'Reunion'),
    ('RUS', 'Russian Federation'),
    ('RWA', 'Rwanda'),
    ('SAU', 'Saudi Arabia'),
    ('SDN', 'Sudan'),
    ('SEN', 'Senegal'),
    ('SGP', 'Singapore'),
    ('SGS', 'South Georgia and the South Sandwich Islands'),
    ('SHN', 'Saint Helena, Ascension and Tristan da Cunha'),
    ('SJM', 'Svalbard and Jan Mayen'),
    ('SLB', 'Solomon Islands'),
    ('SLE', 'Sierra Leone'),
    ('SLV', 'El Salvador'),
    ('SMR', 'San Marino'),
    ('SOM', 'Somalia'),
    ('SPM', 'Saint Pierre and Miquelon'),
    ('SRB', 'Serbia'),
    ('SSD', 'South Sudan'),
    ('STP', 'Sao Tome and Principe'),
    ('SUR', 'Suriname'),
    ('SWZ', 'Eswatini'),
    ('SXM', 'Sint Maarten (Dutch part)'),
    ('SYC', 'Seychelles'),
    ('SYR', 'Syrian Arab Republic'),
    ('TCA', 'Turks and Caicos Islands'),
    ('TCD', 'Chad'),
    ('TGO', 'Togo'),
    ('THA', 'Thailand'),
    ('TJK', 'Tajikistan'),
    ('TKL', 'Tokelau'),
    ('TKM', 'Turkmenistan'),
    ('TLS', 'Timor-Leste'),
    ('TON', 'Tonga'),
    ('TTO', 'Trinidad and Tobago'),
    ('TUN', 'Tunisia'),
    ('TUR', 'Turkey'),
    ('TUV', 'Tuvalu'),
    ('TWN', 'Taiwan'),
    ('TZA', 'Tanzania, United Republic of'),
    ('UGA', 'Uganda'),
    ('UKR', 'Ukraine'),
    ('UMI', 'United States Minor Outlying Islands'),
    ('URY', 'Uruguay'),
    ('USA', 'United States of America'),
    ('UZB', 'Uzbekistan'),
    ('VAT', 'Holy See (Vatican City State)'),
    ('VCT', 'Saint Vincent and the Grenadines'),
    ('VEN', 'Venezuela, Bolivarian Republic of'),
    ('VGB', 'Virgin Islands, British'),
    ('VIR', 'Virgin Islands, U.S.'),
    ('VNM', 'Viet Nam'),
    ('VUT', 'Vanuatu'),
    ('WLF', 'Wallis and Futuna'),
    ('WSM', 'Samoa'),
    ('YEM', 'Yemen'),
    ('ZAF', 'South Africa'),
    ('ZMB', 'Zambia'),
    ('ZWE', 'Zimbabwe'),
]